// Path: src/aln-shell/createAlnShellRepo.js
// Creates a new repo folder pre-populated with the ALN Web Kernel shell.

import fs from "fs";
import path from "path";
import url from "url";

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));

function copyFile(src, dest) {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
}

function writeFile(dest, content) {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, content, "utf8");
}

export function createAlnShellRepo(targetDir) {
  const outDir = path.resolve(process.cwd(), targetDir);
  fs.mkdirSync(outDir, { recursive: true });

  const kernelSrc = path.resolve(
    __dirname,
    "../../examples/aln-shell/aln-augmented-user-kernel.html"
  );
  const wsBridgeSrc = path.resolve(__dirname, "./templates/ws-bridge.js");
  const readmeTemplateSrc = path.resolve(__dirname, "./templates/README.aln-shell.md");

  copyFile(kernelSrc, path.join(outDir, "aln-augmented-user-kernel.html"));
  copyFile(wsBridgeSrc, path.join(outDir, "ws-bridge.js"));
  const readmeContent = fs.readFileSync(readmeTemplateSrc, "utf8");
  writeFile(path.join(outDir, "README.md"), readmeContent);

  const pkgJson = {
    name: "aln-web-kernel-shell",
    version: "0.1.0",
    description:
      "Zero-IDE ALN dashboard shell with WebSocket bridge for EEG/IoT streams, generated by Javaspectre.",
    type: "module",
    main: "ws-bridge.js",
    scripts: {
      start: "node ws-bridge.js"
    },
    dependencies: {
      ws: "^8.18.0"
    }
  };

  writeFile(path.join(outDir, "package.json"), JSON.stringify(pkgJson, null, 2));

  console.log(`[Javaspectre] ALN Web Kernel repo created at: ${outDir}`);
  console.log(`[Javaspectre] Next steps:`);
  console.log(`  cd ${path.relative(process.cwd(), outDir) || "."}`);
  console.log(`  npm install`);
  console.log(`  npm start`);
}
